apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweatherapp
  template:
    metadata:
      labels:
        app: myweatherapp
    spec:
      containers:
        - name: weather-app
          image: jeetlinux/docker-demo:weather

          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp
spec:
  selector:
    app: myweatherapp
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer